### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by dvescovi1** [ms-iot/security#14]
These project seem to be WIN32 x86 projects.
What about ARM support?
I would like to test on RBP platform

**Comment by IoTGirl** [comment]
Hi Stefan,
Could you take a look at this request?
Sincere thanks,
IoTGirl

**Comment by LordOfDorks** [comment]
Last time I checked VS did not support building native Win32 ARM projects. I was able to overcome the compiling problem with some whacky registry hacking, but linking stopped short because the runtime libraries for ARM were not available. I am currently checking with some internal folks to see if this situation has fundamentally changed in VS since then and get back to you.

**Comment by saraclay** [comment]
Closing this issue out for now. If you'd like to file an issue in the future, please do so at: www.github.com/MicrosoftDocs/windows-iotcore-docs
